import React, { useEffect } from 'react';
import { ArrowLeft, CalendarDays, ChevronRight, FileText, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ADMISSION_SCHEDULE, SCHEDULE_NOTES, SCHEDULE_PDF_URL, SCHEDULE_SOURCE, SCHEDULE_SOURCE_NOTE } from '../lib/admissionSchedule';

const ImportantSchedulePage: React.FC = () => {
  useEffect(() => { window.scrollTo(0, 0); }, []);
  const months = [...new Set(ADMISSION_SCHEDULE.map(item => item.month))];
  return <div className="animate-fade-in mx-auto flex w-full max-w-6xl flex-col pb-8">
    <Link to="/" className="mb-7 inline-flex w-fit items-center gap-2 text-sm font-bold text-slate-500 transition hover:text-violet-600"><ArrowLeft className="h-4 w-4" />返回倒數首頁</Link>
    <section className="relative overflow-hidden rounded-[2rem] border border-violet-100 bg-gradient-to-br from-violet-50 via-white to-fuchsia-50 px-6 py-9 shadow-[0_18px_45px_rgba(109,40,217,0.10)] sm:px-10 sm:py-12"><div className="relative"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white/80 px-3 py-1.5 text-xs font-black tracking-[0.14em] text-violet-600"><Sparkles className="h-3.5 w-3.5" />OFFICIAL TIMETABLE</div><h1 className="max-w-3xl text-3xl font-black tracking-tight text-slate-800 sm:text-5xl">116學年度適性入學重要日程</h1><p className="mt-4 max-w-3xl text-sm font-medium leading-7 text-slate-600 sm:text-base">完整整理國中教育會考、高級中等學校與五專各入學管道的重要日期，依月份查看更容易安排準備進度。</p><div className="mt-6 flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-2 rounded-2xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white shadow-lg shadow-violet-200"><CalendarDays className="h-4 w-4" />會考：116年5月15日至16日</span><a href={SCHEDULE_PDF_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-2xl border border-violet-200 bg-white px-4 py-2.5 text-sm font-black text-violet-700 hover:bg-violet-50"><FileText className="h-4 w-4" />查看原始日程表 PDF</a></div></div></section>
    <div className="mt-8 grid gap-6 lg:grid-cols-2">{months.map(month => <section key={month} className="rounded-[2rem] border border-[#eadfce] bg-[#fffdfa] p-5 shadow-[0_14px_35px_rgba(65,51,31,0.07)] sm:p-7"><h2 className="mb-5 flex items-center gap-3 text-2xl font-black text-slate-800"><span className="rounded-xl bg-violet-100 px-3 py-1 text-violet-700">{month}月</span><span className="text-sm font-medium text-slate-500">重要辦理事項</span></h2><ol className="space-y-3">{ADMISSION_SCHEDULE.filter(item => item.month === month).map((item, index) => <li key={`${item.start}-${item.task}`} className={`rounded-2xl border p-4 ${item.isHighlight ? 'border-violet-200 bg-violet-50/80' : 'border-slate-100 bg-slate-50/70'}`}><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between sm:gap-4"><div className="flex gap-3"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-white text-[10px] font-black text-violet-600 ring-1 ring-violet-100">{String(index + 1).padStart(2, '0')}</span><p className={`text-sm font-black leading-6 ${item.isHighlight ? 'text-violet-800' : 'text-slate-700'}`}>{item.task}</p></div><span className={`shrink-0 text-xs font-black ${item.isHighlight ? 'text-violet-700' : 'text-slate-500'}`}>{item.date}</span></div></li>)}</ol></section>)}</div>
    <section className="mt-7 rounded-[2rem] border border-amber-100 bg-amber-50/70 p-6"><h2 className="text-lg font-black text-amber-900">日程表備註</h2><p className="mt-1 text-xs font-bold text-amber-700">{SCHEDULE_SOURCE}｜{SCHEDULE_SOURCE_NOTE}</p><ul className="mt-4 space-y-2 text-sm leading-6 text-slate-700">{SCHEDULE_NOTES.map(note => <li key={note} className="flex gap-2"><span className="font-black text-amber-500">•</span>{note}</li>)}</ul></section>
    <Link to="/schedule" className="group mt-7 flex items-center justify-between rounded-2xl border border-blue-100 bg-blue-50/70 px-5 py-4 text-sm font-black text-blue-800 transition hover:border-blue-200 hover:bg-blue-50"><span>查看詳細考試作息與應試提醒</span><ChevronRight className="h-5 w-5 transition-transform group-hover:translate-x-1" /></Link>
  </div>;
};
export default ImportantSchedulePage;
