import React from 'react';
import { ArrowUpRight, Heart, Mail, Sparkles } from 'lucide-react';

const SiteFooter: React.FC = () => (
  <footer className="relative mt-8 w-full overflow-hidden border-t border-[#193968] bg-[#10264e] text-white shadow-[0_-10px_28px_rgba(16,38,78,0.12)]">
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_85%_0%,rgba(255,191,91,0.18),transparent_32%)]"></div>
    <div className="relative mx-auto grid w-full max-w-6xl gap-6 px-5 py-8 sm:px-8 md:grid-cols-[1fr_auto_auto] md:items-center md:gap-8 md:py-5">
      <a href="https://tyctw.github.io/spare/" target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.06] p-4 transition hover:bg-white/10 md:border-0 md:bg-transparent md:p-0"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#ffbf5b] text-[#10264e] shadow-lg shadow-black/10"><Sparkles className="h-5 w-5" /></span><span><span className="mb-0.5 block text-base font-black tracking-tight">116 會考倒數</span><span className="block text-xs font-medium text-blue-100/65">每一份努力，都算數。</span></span></a>
      <nav className="grid grid-cols-2 gap-2 text-xs font-bold md:flex md:items-center md:gap-4"><a href="https://tyctw.github.io/spare/?route=/scoring-rules/taipei" target="_blank" rel="noopener noreferrer" className="rounded-xl border border-white/10 bg-white/[0.06] px-3 py-3 text-center text-blue-100/85 transition hover:border-[#ffcf7d]/50 hover:text-[#ffcf7d] md:border-0 md:bg-transparent md:px-0 md:py-1">基北區會考落點</a><a href="https://tyctw.github.io/spare/?route=/scoring-rules/taoyuan" target="_blank" rel="noopener noreferrer" className="rounded-xl border border-white/10 bg-white/[0.06] px-3 py-3 text-center text-blue-100/85 transition hover:border-[#ffcf7d]/50 hover:text-[#ffcf7d] md:border-0 md:bg-transparent md:px-0 md:py-1">桃連區會考落點</a><a href="https://tyctw.github.io/spare/?route=/scoring-rules/central" target="_blank" rel="noopener noreferrer" className="rounded-xl border border-white/10 bg-white/[0.06] px-3 py-3 text-center text-blue-100/85 transition hover:border-[#ffcf7d]/50 hover:text-[#ffcf7d] md:border-0 md:bg-transparent md:px-0 md:py-1">中投區會考落點</a><a href="mailto:tyctw.analyze@gmail.com" className="inline-flex items-center justify-center gap-1.5 rounded-xl border border-white/10 bg-white/[0.06] px-3 py-3 text-blue-100/85 transition hover:border-white/30 hover:text-white md:border-0 md:bg-transparent md:px-0 md:py-1"><Mail className="h-3.5 w-3.5" />聯絡我們</a></nav>
      <a href="https://tyctw.github.io/spare/support/" target="_blank" rel="noopener noreferrer" className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-[#ffcf7d]/35 bg-[#ffbf5b] px-4 py-3 text-sm font-black text-[#10264e] shadow-lg shadow-black/10 transition hover:-translate-y-0.5 hover:bg-[#ffcf7d] md:w-auto md:rounded-full md:px-4 md:py-2"><Heart className="h-4 w-4 fill-current" />支持免費工具持續維護<ArrowUpRight className="h-4 w-4" /></a>
    </div>
    <div className="relative border-t border-white/10 bg-black/10 py-2 text-center text-[10px] font-medium text-blue-100/50">© {new Date().getFullYear()} TYCTW Analyze</div>
  </footer>
);

export default SiteFooter;
